AWSTemplateFormatVersion: 2010-09-09

Parameters:

  authUrl:
    Type: String

  publicKey:
    Type: String

  cookieName:
    Type: String

  publicPathPattern:
    Type: String
    Default: "*.png"

  contentBucket:
    Type: String

  logBucket:
    Type: String

  sslCertificateArn:
    Type: String

  domainName:
    Type: String

Resources:

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref AWS::StackName

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Ref AWS::StackName
        Enabled: True
        PriceClass: PriceClass_100
        Aliases:
        - !Ref domainName
        ViewerCertificate:
          AcmCertificateArn: !Ref sslCertificateArn
          SslSupportMethod: sni-only
        Origins:
        - Id: !Ref contentBucket
          DomainName: !Sub "${contentBucket}.s3.amazonaws.com"
          S3OriginConfig:
            OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${OriginAccessIdentity}"
        CacheBehaviors:
        - PathPattern: !Ref publicPathPattern
          ForwardedValues:
            QueryString: False
          TargetOriginId: !Ref contentBucket
          ViewerProtocolPolicy: redirect-to-https
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: !Ref contentBucket
          ViewerProtocolPolicy: redirect-to-https
          LambdaFunctionAssociations:
          - EventType: viewer-request
            LambdaFunctionARN: !Ref LambdaVersionREPLACE
        Logging:
          Bucket: !Sub "${logBucket}.s3.amazonaws.com"
          Prefix: !Ref AWS::StackName
          IncludeCookies: true

  ViewerRequestStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        name: !Sub "${AWS::StackName}-viewer-request"
        authUrl: !Ref authUrl
        domainName: !Ref domainName
        cookieName: !Ref cookieName
        publicKey: !Ref publicKey
      TemplateURL: viewer-request/cloudformation.yaml

  LambdaVersionREPLACE:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !GetAtt ViewerRequestStack.Outputs.LambdaName
