AWSTemplateFormatVersion: 2010-09-09

Parameters:

  ursClientId:
    Type: String

  ursClientPassword:
    Type: String
    NoEcho: true

  secretKey:
    Type: String
    MinLength: 32
    NoEcho: true

  ursHostname:
    Type: String
    AllowedValues:
    - https://uat.urs.earthdata.nasa.gov
    - https://urs.earthdata.nasa.gov
    Default: https://urs.earthdata.nasa.gov

  sessionDurationInSeconds:
    Type: Number
    MinValue: 0
    Default: 86400

  elasticSearchCidrIp:
    Type: String

Outputs:

  DomainName:
    Value: !GetAtt Distribution.DomainName

Resources:

  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-content"

  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-logs"

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref AWS::StackName

  ContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ContentBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
          Resource: !Sub "${ContentBucket.Arn}/*"
          Action: s3:GetObject
        - Effect: Allow
          Principal:
            CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
          Resource: !Sub "${ContentBucket.Arn}"
          Action: s3:ListBucket

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Ref AWS::StackName
        Enabled: True
        PriceClass: PriceClass_100
        Origins:
        - Id: !Ref ContentBucket
          DomainName: !GetAtt ContentBucket.DomainName
          S3OriginConfig:
            OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${OriginAccessIdentity}"
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: !Ref ContentBucket
          ViewerProtocolPolicy: redirect-to-https
          LambdaFunctionAssociations:
          - EventType: viewer-request
            LambdaFunctionARN: !Ref LambdaVersionREPLACE
        Logging:
          Bucket: !GetAtt LogBucket.DomainName
          Prefix: cloudfront/
          IncludeCookies: true

  ElasticSearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: !Ref AWS::StackName
      ElasticsearchVersion: 7.1
      AccessPolicies: !Sub |-
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "AWS": "*"
              },
              "Action": [
                "es:ESHttpGet",
                "es:ESHttpPut",
                "es:ESHttpPost",
                "es:ESHttpDelete",
                "es:ESHttpHead"
              ],
              "Resource": "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${AWS::StackName}/*",
              "Condition": {
                "IpAddress": {
                  "aws:SourceIp": "${elasticSearchCidrIp}"
                }
              }
            }
          ]
        }
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: false
        InstanceCount: 1
        InstanceType: t2.small.elasticsearch
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp2

  ViewerRequestStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        name: !Sub "${AWS::StackName}-viewer-request"
        ursClientId: !Ref ursClientId
        ursClientPassword: !Ref ursClientPassword
        secretKey: !Ref secretKey
        ursHostname: !Ref ursHostname
        sessionDurationInSeconds: !Ref sessionDurationInSeconds
      TemplateURL: viewer-request/cloudformation.yaml

  LambdaVersionREPLACE:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !GetAtt ViewerRequestStack.Outputs.LambdaName
